<a href="https://colab.research.google.com/github/shreyaa008/ai-from-scratch/blob/main/NumPy_practice.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

In [ ]:
number = np.array([5,10,15,20,25])
print(number*3)

[15 30 45 60 75]


In [ ]:
number = np.array([10,20,30,40])
print(number+7)

[17 27 37 47]


In [ ]:
arr = np.array([5, 10, 15, 20])
print(arr.shape)
print(arr.ndim)
print(arr.size)

(4,)
1
4


In [ ]:
arr = np.array([[10, 20, 30, 40],[50, 60, 70, 80],[90, 100, 110, 120]])
print(arr[0:2, 1:3])

[[20 30]
 [60 70]]


In [ ]:
arr=np.zeros(4, dtype=int)
print(arr)

[0 0 0 0]


In [ ]:
arr=np.ones((2, 3))
print(arr)

[[1. 1. 1.]
 [1. 1. 1.]]


In [ ]:
arr=np.arange(1, 10, 2)
print(arr)


[1 3 5 7 9]


In [ ]:
arr=np.linspace(0, 20, 5)
print(arr)

[ 0.  5. 10. 15. 20.]
